name: Build

on:
  push:
    branches:
      - main
      
env:
  PROJECT: "**/Papyrus.csproj"
  BUILD_CONFIGURATION: Release
        
jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Use .NET 7 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.101
          
      - name: Build
        run: |
          dotnet build ${{ env.PROJECT }} --configuration ${{ env.BUILD_CONFIGURATION }}
